server:
 port: 7001
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: true #设置为false表示关闭保护模式 页面上访问会出现红色提示。
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
#        admin:enjoy@ 这个是设置往注册中心注册服务的账号、密码
        defaultZone: http://admin:enjoy@127.0.0.1:7001/eureka
#        defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance: # eureak实例定义
    hostname: eureka1 # 定义 Eureka 实例所在的主机名称,这里指定了名称以后需要在hosts配置文件里面进行配置
# 给注册中心设置用户名、密码
spring:
  application:
    name: eureka
  security:
    user:
      name: admin
      password: enjoy1

hello: hello